## 🔹 Part 1 — Data Processing & Feature Engineering

In [1]:
# Load the datasets
import pandas as pd
import os

# Define base folder path
DATA_PATH = "store_sales_data"

# Load datasets using os.path.join
train_df = pd.read_csv(os.path.join(DATA_PATH, "train.csv"), parse_dates=["date"])
test_df = pd.read_csv(os.path.join(DATA_PATH, "test.csv"), parse_dates=["date"])
store_df = pd.read_csv(os.path.join(DATA_PATH, "stores.csv"))
oil_df = pd.read_csv(os.path.join(DATA_PATH, "oil.csv"), parse_dates=["date"])
transactions_df = pd.read_csv(os.path.join(DATA_PATH, "transactions.csv"), parse_dates=["date"])
holidays_events_df = pd.read_csv(os.path.join(DATA_PATH, "holidays_events.csv"), parse_dates=["date"])

### Check top five rows of each dataframe

In [2]:

train_df.head(5)

   id       date  store_nbr      family  sales  onpromotion
0   0 2013-01-01          1  AUTOMOTIVE    0.0            0
1   1 2013-01-01          1   BABY CARE    0.0            0
2   2 2013-01-01          1      BEAUTY    0.0            0
3   3 2013-01-01          1   BEVERAGES    0.0            0
4   4 2013-01-01          1       BOOKS    0.0            0

In [3]:
test_df.head(5)

        id       date  store_nbr      family  onpromotion
0  3000888 2017-08-16          1  AUTOMOTIVE            0
1  3000889 2017-08-16          1   BABY CARE            0
2  3000890 2017-08-16          1      BEAUTY            2
3  3000891 2017-08-16          1   BEVERAGES           20
4  3000892 2017-08-16          1       BOOKS            0

In [4]:
transactions_df.head(5)

        date  store_nbr  transactions
0 2013-01-01         25           770
1 2013-01-02          1          2111
2 2013-01-02          2          2358
3 2013-01-02          3          3487
4 2013-01-02          4          1922

In [5]:
store_df.head(5)

   store_nbr           city                           state type  cluster
0          1          Quito                       Pichincha    D       13
1          2          Quito                       Pichincha    D       13
2          3          Quito                       Pichincha    D        8
3          4          Quito                       Pichincha    D        9
4          5  Santo Domingo  Santo Domingo de los Tsachilas    D        4

In [6]:
oil_df.head()

        date  dcoilwtico
0 2013-01-01         NaN
1 2013-01-02       93.14
2 2013-01-03       92.97
3 2013-01-04       93.12
4 2013-01-07       93.20

In [7]:
holidays_events_df.head(5)

,date,type,locale,locale_name,description,transferred
0,2012-03-02,Holiday,Local,Manta,Fundacion de Manta,False
1,2012-04-01,Holiday,Regional,Cotopaxi,Provincializacion de Cotopaxi,False
2,2012-04-12,Holiday,Local,Cuenca,Fundacion de Cuenca,False
3,2012-04-14,Holiday,Local,Libertad,Cantonizacion de Libertad,False
4,2012-04-21,Holiday,Local,Riobamba,Cantonizacion de Riobamba,False

In [8]:
# Create a dictionary of your DataFrames
all_dfs = {
    "train": train_df,
    "test": test_df,
    "store": store_df,
    "transactions": transactions_df,
    "oil": oil_df,
    "holidays_events": holidays_events_df
}

# Loop through the dictionary and print the null counts
print("Total Missing Values per DataFrame:")
for name, df in all_dfs.items():
    total_nulls = df.isnull().sum().sum()
    print(f"- {name}_df: {total_nulls}")

Total Missing Values per DataFrame:
- train_df: 0
- test_df: 0
- store_df: 0
- transactions_df: 0
- oil_df: 43
- holidays_events_df: 0

In [9]:
oil_df['dcoilwtico'] = oil_df['dcoilwtico'].interpolate()
oil_df['dcoilwtico'] = oil_df['dcoilwtico'].fillna(method='bfill') # type: ignore

/tmp/ipykernel_3698/194301098.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  oil_df['dcoilwtico'] = oil_df['dcoilwtico'].fillna(method='bfill') # type: ignore

In [10]:
oil_df.isnull().sum()

date          0
dcoilwtico    0
dtype: int64

In [11]:
train_df.columns

Index(['id', 'date', 'store_nbr', 'family', 'sales', 'onpromotion'], dtype='object')

In [12]:
train_df.describe()

,id,date,store_nbr,sales,onpromotion
count,3.000888e+06,3000888,3.000888e+06,3.000888e+06,3.000888e+06
mean,1.500444e+06,2015-04-24 08:27:04.703088384,2.750000e+01,3.577757e+02,2.602770e+00
min,0.000000e+00,2013-01-01 00:00:00,1.000000e+00,0.000000e+00,0.000000e+00
25%,7.502218e+05,2014-02-26 18:00:00,1.400000e+01,0.000000e+00,0.000000e+00
50%,1.500444e+06,2015-04-24 12:00:00,2.750000e+01,1.100000e+01,0.000000e+00
75%,2.250665e+06,2016-06-19 06:00:00,4.100000e+01,1.958473e+02,0.000000e+00
max,3.000887e+06,2017-08-15 00:00:00,5.400000e+01,1.247170e+05,7.410000e+02
std,8.662819e+05,NaN,1.558579e+01,1.101998e+03,1.221888e+01

In [13]:
len(train_df["family"].unique())

33

In [14]:
test_df.describe()

                 id                 date     store_nbr   onpromotion
count  2.851200e+04                28512  28512.000000  28512.000000
mean   3.015144e+06  2017-08-23 12:00:00     27.500000      6.965383
min    3.000888e+06  2017-08-16 00:00:00      1.000000      0.000000
25%    3.008016e+06  2017-08-19 18:00:00     14.000000      0.000000
50%    3.015144e+06  2017-08-23 12:00:00     27.500000      0.000000
75%    3.022271e+06  2017-08-27 06:00:00     41.000000      6.000000
max    3.029399e+06  2017-08-31 00:00:00     54.000000    646.000000
std    8.230850e+03                  NaN     15.586057     20.683952

In [15]:
print(train_df.shape)
print(oil_df.shape)

(3000888, 6)
(1218, 2)

In [16]:
train_oil_df = train_df.merge(oil_df, on="date", how="left")

In [17]:
train_oil_df.isnull().sum().sum()

np.int64(857142)

In [18]:
train_oil_df.isnull().sum()

id                  0
date                0
store_nbr           0
family              0
sales               0
onpromotion         0
dcoilwtico     857142
dtype: int64

In [19]:
train_oil_df["dcoilwtico"] = train_oil_df["dcoilwtico"].fillna(method="bfill") # type: ignore

/tmp/ipykernel_3698/3675405296.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  train_oil_df["dcoilwtico"] = train_oil_df["dcoilwtico"].fillna(method="bfill") # type: ignore

In [20]:
train_oil_df.isnull().sum()

id             0
date           0
store_nbr      0
family         0
sales          0
onpromotion    0
dcoilwtico     0
dtype: int64

In [21]:
print(f"train_df shape: {train_df.shape}")
print(f"train_oil_df shape: {train_oil_df.shape}")

train_df shape: (3000888, 6)
train_oil_df shape: (3000888, 7)

In [22]:
holidays_events_df.head(5)

,date,type,locale,locale_name,description,transferred
0,2012-03-02,Holiday,Local,Manta,Fundacion de Manta,False
1,2012-04-01,Holiday,Regional,Cotopaxi,Provincializacion de Cotopaxi,False
2,2012-04-12,Holiday,Local,Cuenca,Fundacion de Cuenca,False
3,2012-04-14,Holiday,Local,Libertad,Cantonizacion de Libertad,False
4,2012-04-21,Holiday,Local,Riobamba,Cantonizacion de Riobamba,False

In [23]:
holidays_events_df["type"].unique()

array(['Holiday', 'Transfer', 'Additional', 'Bridge', 'Work Day', 'Event'],
      dtype=object)

In [24]:
holidays_events_df.shape

(350, 6)

In [25]:
store_df.columns

Index(['store_nbr', 'city', 'state', 'type', 'cluster'], dtype='object')

In [26]:
train_oil_store_df = train_oil_df.merge(store_df, on='store_nbr', how='left')
train_oil_store_df.head(5)

,id,date,store_nbr,family,sales,onpromotion,dcoilwtico,city,state,type,cluster
0,0,2013-01-01,1,AUTOMOTIVE,0.0,0,93.14,Quito,Pichincha,D,13
1,1,2013-01-01,1,BABY CARE,0.0,0,93.14,Quito,Pichincha,D,13
2,2,2013-01-01,1,BEAUTY,0.0,0,93.14,Quito,Pichincha,D,13
3,3,2013-01-01,1,BEVERAGES,0.0,0,93.14,Quito,Pichincha,D,13
4,4,2013-01-01,1,BOOKS,0.0,0,93.14,Quito,Pichincha,D,13

In [27]:
train_oil_store_df.isnull().sum().sum()

np.int64(0)

In [28]:
holidays_events_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         350 non-null    datetime64[ns]
 1   type         350 non-null    object
 2   locale       350 non-null    object
 3   locale_name  350 non-null    object
 4   description  350 non-null    object
 5   transferred  350 non-null    bool
dtypes: bool(1), datetime64[ns](1), object(4)
memory usage: 14.1+ KB

In [29]:
# removed tranfereed columns
holidays_events_df = holidays_events_df[holidays_events_df['transferred'] == False]
holidays_events_df.shape

(338, 6)

In [30]:
holidays_events_df['type'].unique()

array(['Holiday', 'Transfer', 'Additional', 'Bridge', 'Work Day', 'Event'],
      dtype=object)

In [31]:
holidays_events_df = holidays_events_df[holidays_events_df['type'] != 'Work Day']
holidays_events_df.shape

(333, 6)

In [32]:
train_oil_store_df.head(5)

,id,date,store_nbr,family,sales,onpromotion,dcoilwtico,city,state,type,cluster
0,0,2013-01-01,1,AUTOMOTIVE,0.0,0,93.14,Quito,Pichincha,D,13
1,1,2013-01-01,1,BABY CARE,0.0,0,93.14,Quito,Pichincha,D,13
2,2,2013-01-01,1,BEAUTY,0.0,0,93.14,Quito,Pichincha,D,13
3,3,2013-01-01,1,BEVERAGES,0.0,0,93.14,Quito,Pichincha,D,13
4,4,2013-01-01,1,BOOKS,0.0,0,93.14,Quito,Pichincha,D,13

In [33]:
holidays_events_df.columns

Index(['date', 'type', 'locale', 'locale_name', 'description', 'transferred'], dtype='object')

In [34]:
holidays_events_df['locale'].unique()

array(['Local', 'Regional', 'National'], dtype=object)

In [35]:
train_oil_store_holiday_df = train_oil_store_df.merge(holidays_events_df, on='date', how='left')

In [ ]:
train_oil_store_holiday_df.head(5)

In [ ]:
train_oil_store_holiday_df['holiday_flag'] = 0

In [38]:
train_oil_store_holiday_df.loc[train_oil_store_holiday_df['locale'] == 'National', 'holiday_flag'] = 1

train_oil_store_holiday_df.loc[
    (train_oil_store_holiday_df['locale'] == 'Regional') &
    (train_oil_store_holiday_df['locale_name'] == train_oil_store_holiday_df['state']),
    'holiday_flag'
] = 1

train_oil_store_holiday_df.loc[
    (train_oil_store_holiday_df['locale'] == 'Local') &
    (train_oil_store_holiday_df['locale_name'] == train_oil_store_holiday_df['city']),
    'holiday_flag'
] = 1

In [39]:
train_oil_store_holiday_df.head(5)

,id,date,store_nbr,family,sales,onpromotion,dcoilwtico,city,state,type_x,cluster,type_y,locale,locale_name,description,transferred,holiday_flag
0,0,2013-01-01,1,AUTOMOTIVE,0.0,0,93.14,Quito,Pichincha,D,13,Holiday,National,Ecuador,Primer dia del ano,False,1.0
1,1,2013-01-01,1,BABY CARE,0.0,0,93.14,Quito,Pichincha,D,13,Holiday,National,Ecuador,Primer dia del ano,False,1.0
2,2,2013-01-01,1,BEAUTY,0.0,0,93.14,Quito,Pichincha,D,13,Holiday,National,Ecuador,Primer dia del ano,False,1.0
3,3,2013-01-01,1,BEVERAGES,0.0,0,93.14,Quito,Pichincha,D,13,Holiday,National,Ecuador,Primer dia del ano,False,1.0
4,4,2013-01-01,1,BOOKS,0.0,0,93.14,Quito,Pichincha,D,13,Holiday,National,Ecuador,Primer dia del ano,False,1.0

In [40]:
train_df_final = train_oil_store_holiday_df

In [41]:
train_df_final.columns

Index(['id', 'date', 'store_nbr', 'family', 'sales', 'onpromotion',
       'dcoilwtico', 'city', 'state', 'type_x', 'cluster', 'type_y', 'locale',
       'locale_name', 'description', 'transferred', 'holiday_flag'],
      dtype='object')

In [42]:
train_df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3052566 entries, 0 to 3052565
Data columns (total 17 columns):
 #   Column        Dtype
---  ------        -----
 0   id            int64
 1   date          datetime64[ns]
 2   store_nbr     int64
 3   family        object
 4   sales         float64
 5   onpromotion   int64
 6   dcoilwtico    float64
 7   city          object
 8   state         object
 9   type_x        object
 10  cluster       int64
 11  type_y        object
 12  locale        object
 13  locale_name   object
 14  description   object
 15  transferred   object
 16  holiday_flag  float64
dtypes: datetime64[ns](1), float64(3), int64(4), object(9)
memory usage: 395.9+ MB

In [43]:
holidays_events_df.columns

Index(['date', 'type', 'locale', 'locale_name', 'description', 'transferred'], dtype='object')

In [44]:
train_df_final.drop(["type_y", "type_x", "description", "transferred"], axis=1, inplace=True)

In [45]:
train_df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3052566 entries, 0 to 3052565
Data columns (total 13 columns):
 #   Column        Dtype
---  ------        -----
 0   id            int64
 1   date          datetime64[ns]
 2   store_nbr     int64
 3   family        object
 4   sales         float64
 5   onpromotion   int64
 6   dcoilwtico    float64
 7   city          object
 8   state         object
 9   cluster       int64
 10  locale        object
 11  locale_name   object
 12  holiday_flag  float64
dtypes: datetime64[ns](1), float64(3), int64(4), object(5)
memory usage: 302.8+ MB

In [46]:
train_df_full = train_df_final.merge(transactions_df, on=["store_nbr", "date"], how="left")

In [47]:
train_df_full.isnull().sum()

id                    0
date                  0
store_nbr             0
family                0
sales                 0
onpromotion           0
dcoilwtico            0
city                  0
state                 0
cluster               0
locale          2574990
locale_name     2574990
holiday_flag    2798829
transactions     249051
dtype: int64